### ISSUE TITLE
Add liquid wallet support to Shopstr's wallet

### ISSUE THREAD

**Issue by welliv** [shopstr-eng/shopstr#74]
I'm opening this issue as the work on Shopstr's Liquid wallet has begun. This issue strives to describe the expectations and track the progress, in the linked PR.

This is powered by `lwk_wasm` library from Blockstream.

The code is being worked on is located in `feat/integrate-liquid-wallet` branch.

### Tasks

- [x] Generate a watch-only wallet
- [x] Allow importing of existing wallets by confidential descriptor
- [x] Integrate lightning <-> liquid swaps using Boltz

### Walkthrough
- [x] https://drive.proton.me/urls/WV01BRJC1G#vrEBbsQShTyB

**Comment by Shopstr-LiquidDev** [comment]
During the past 2 weeks I've implemented also the recovery mechanism for the wallet, added fiat api and also added embedded boltz.exchange swap into the app.
